<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="JKASHYAPSSL" name="Com.Testcases.Claim_Reserve_PaymentVerfication_fromDatabase" tests="10" failures="0" timestamp="14 Dec 2017 14:06:32 GMT" time="2458.442" errors="3">
  <testcase name="Test_ReserveAndPayment_Verification_FromDatabase" time="236.166" classname="Com.Testcases.Claim_Reserve_PaymentVerfication_fromDatabase"/>
  <testcase name="Test_ReserveAndPayment_Verification_FromDatabase" time="337.332" classname="Com.Testcases.Claim_Reserve_PaymentVerfication_fromDatabase"/>
  <testcase name="Test_ReserveAndPayment_Verification_FromDatabase" time="127.290" classname="Com.Testcases.Claim_Reserve_PaymentVerfication_fromDatabase">
    <error type="java.lang.AssertionError" message="expected [5,000.00] but found [50.00]">
      <![CDATA[java.lang.AssertionError: expected [5,000.00] but found [50.00]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at Com.Testcases.Claim_Reserve_PaymentVerfication_fromDatabase.Test_ReserveAndPayment_Verification_FromDatabase(Claim_Reserve_PaymentVerfication_fromDatabase.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- Test_ReserveAndPayment_Verification_FromDatabase -->
  <testcase name="Test_ReserveAndPayment_Verification_FromDatabase" time="129.691" classname="Com.Testcases.Claim_Reserve_PaymentVerfication_fromDatabase">
    <error type="java.lang.AssertionError" message="expected [5,000.00] but found [500.00]">
      <![CDATA[java.lang.AssertionError: expected [5,000.00] but found [500.00]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at Com.Testcases.Claim_Reserve_PaymentVerfication_fromDatabase.Test_ReserveAndPayment_Verification_FromDatabase(Claim_Reserve_PaymentVerfication_fromDatabase.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- Test_ReserveAndPayment_Verification_FromDatabase -->
  <testcase name="Test_ReserveAndPayment_Verification_FromDatabase" time="238.799" classname="Com.Testcases.Claim_Reserve_PaymentVerfication_fromDatabase"/>
  <testcase name="Test_ReserveAndPayment_Verification_FromDatabase" time="130.744" classname="Com.Testcases.Claim_Reserve_PaymentVerfication_fromDatabase">
    <error type="java.lang.AssertionError" message="expected [500.00] but found [50.00]">
      <![CDATA[java.lang.AssertionError: expected [500.00] but found [50.00]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at Com.Testcases.Claim_Reserve_PaymentVerfication_fromDatabase.Test_ReserveAndPayment_Verification_FromDatabase(Claim_Reserve_PaymentVerfication_fromDatabase.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- Test_ReserveAndPayment_Verification_FromDatabase -->
  <testcase name="Test_ReserveAndPayment_Verification_FromDatabase" time="334.359" classname="Com.Testcases.Claim_Reserve_PaymentVerfication_fromDatabase"/>
  <testcase name="Test_ReserveAndPayment_Verification_FromDatabase" time="343.897" classname="Com.Testcases.Claim_Reserve_PaymentVerfication_fromDatabase"/>
  <testcase name="Test_ReserveAndPayment_Verification_FromDatabase" time="339.937" classname="Com.Testcases.Claim_Reserve_PaymentVerfication_fromDatabase"/>
  <testcase name="Test_ReserveAndPayment_Verification_FromDatabase" time="240.227" classname="Com.Testcases.Claim_Reserve_PaymentVerfication_fromDatabase"/>
</testsuite> <!-- Com.Testcases.Claim_Reserve_PaymentVerfication_fromDatabase -->
